import { AdminNotice, AdminPageHeader } from "@/components/admin/admin-page-header";
import { SubmitButton } from "@/components/admin/submit-button";
import { saveSettingsAction } from "@/app/admin/actions";
import { getSettings } from "@/lib/public-data";

export default async function AdminContentPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
  const [query,settings]=await Promise.all([searchParams,getSettings()]);
  return <><AdminPageHeader eyebrow="KONTEN UTAMA" title="Profil & kontak" copy="Perbarui teks beranda, sejarah, visi-misi, kanal resmi, dan tautan formulir."/><AdminNotice saved={query.saved} error={query.error}/><section className="admin-editor admin-editor--always"><form action={saveSettingsAction} className="admin-form"><div className="admin-form-section"><span>01</span><div><p>BERANDA</p><h2>Pesan utama</h2></div></div><div className="field field--wide"><label htmlFor="heroTitle">Judul hero</label><input id="heroTitle" name="heroTitle" defaultValue={settings.heroTitle} required/></div><div className="field field--wide"><label htmlFor="heroSubtitle">Deskripsi hero</label><textarea id="heroSubtitle" name="heroSubtitle" rows={3} defaultValue={settings.heroSubtitle} required/></div><div className="admin-form-section"><span>02</span><div><p>PROFIL ORGANISASI</p><h2>Sejarah, visi, dan misi</h2></div></div><div className="field field--wide"><label htmlFor="history">Sejarah singkat</label><textarea id="history" name="history" rows={7} defaultValue={settings.history} required/></div><div className="field field--wide"><label htmlFor="vision">Visi</label><textarea id="vision" name="vision" rows={4} defaultValue={settings.vision} required/></div><div className="field field--wide"><label htmlFor="mission">Misi</label><textarea id="mission" name="mission" rows={7} defaultValue={settings.mission.join("\n")} required/><small>Tulis satu butir misi per baris.</small></div><div className="admin-form-section"><span>03</span><div><p>KONTAK & FORMULIR</p><h2>Kanal resmi</h2></div></div><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" defaultValue={settings.email} required/></div><div className="field"><label htmlFor="whatsapp">WhatsApp (opsional)</label><input id="whatsapp" name="whatsapp" defaultValue={settings.whatsapp} placeholder="628123456789"/></div><div className="field"><label htmlFor="instagramUrl">URL Instagram</label><input id="instagramUrl" name="instagramUrl" type="url" defaultValue={settings.instagramUrl} required/></div><div className="field"><label htmlFor="youtubeUrl">URL YouTube</label><input id="youtubeUrl" name="youtubeUrl" type="url" defaultValue={settings.youtubeUrl} required/></div><div className="field"><label htmlFor="memberFormUrl">Form pendaftaran anggota</label><input id="memberFormUrl" name="memberFormUrl" type="url" defaultValue={settings.memberFormUrl} placeholder="Kosongkan jika belum tersedia"/></div><div className="field"><label htmlFor="loanFormUrl">Form peminjaman alat</label><input id="loanFormUrl" name="loanFormUrl" type="url" defaultValue={settings.loanFormUrl} required/></div><div className="admin-form__actions admin-form__actions--sticky"><SubmitButton/></div></form></section></>;
}
