import Link from "next/link";
import { ArrowRight, CalendarDays, Compass, Images, MapPin, UsersRound } from "lucide-react";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { getDashboardCounts } from "@/lib/admin-data";
import { formatCompactDate, formatEventDate } from "@/lib/format";
import { getEvents } from "@/lib/public-data";

export default async function AdminDashboard() {
  const [counts, events] = await Promise.all([getDashboardCounts(), getEvents(true)]);
  const next = events.find((event) => event.status === "published" && event.startAt >= new Date());
  const metrics = [["Event", counts.events, CalendarDays, "/admin/event"], ["Media", counts.gallery, Images, "/admin/galeri"], ["Divisi", counts.divisions, Compass, "/admin/divisi"], ["Pengurus", counts.members, UsersRound, "/admin/pengurus"]] as const;
  return <><AdminPageHeader eyebrow="RINGKASAN" title="Selamat datang di basecamp." copy="Kelola informasi yang dilihat anggota, calon anggota, dan publik." /><section className="admin-metrics">{metrics.map(([label,count,Icon,href])=><Link href={href} key={label}><Icon size={20}/><span>{label}</span><strong>{count}</strong><ArrowRight size={17}/></Link>)}</section><section className="admin-dashboard-grid"><div className="admin-panel"><div className="admin-panel__heading"><div><p>AGENDA TERDEKAT</p><h2>Siap diberangkatkan</h2></div><Link href="/admin/event">Kelola event</Link></div>{next?<article className="admin-next-event"><time><strong>{formatCompactDate(next.startAt).day}</strong><span>{formatCompactDate(next.startAt).month}</span></time><div><span>{formatEventDate(next.startAt,next.endAt)}</span><h3>{next.title}</h3><p><MapPin size={14}/>{next.location}</p></div><Link href={`/event/${next.slug}`} target="_blank"><ArrowRight/></Link></article>:<div className="admin-empty"><CalendarDays/><p>Belum ada event publik mendatang.</p><Link href="/admin/event?new=1">Tambah event</Link></div>}</div><div className="admin-panel admin-quick"><div className="admin-panel__heading"><div><p>AKSES CEPAT</p><h2>Yang sering dikerjakan</h2></div></div><Link href="/admin/galeri?new=1"><span>Tambah dokumentasi</span><ArrowRight/></Link><Link href="/admin/event?new=1"><span>Terbitkan event</span><ArrowRight/></Link><Link href="/admin/konten"><span>Perbarui profil</span><ArrowRight/></Link><Link href="/admin/pengurus"><span>Susun pengurus</span><ArrowRight/></Link></div></section><section className="admin-guide"><div><span>01</span><p><strong>Siapkan konten</strong>Pastikan judul, tanggal, dan tautan sudah benar.</p></div><div><span>02</span><p><strong>Tinjau tampilan</strong>Buka website publik setelah menyimpan perubahan.</p></div><div><span>03</span><p><strong>Jaga akses</strong>Buat akun terpisah untuk setiap pengurus.</p></div></section></>;
}
